openapi: 3.0.3
info:
  title: EmporioLambda BE
  description: OpenAPI for products management
  version: 0.1.0

servers:
# Added by API Auto Mocking Plugin
- description: SwaggerHub API Auto Mocking
  url: https://virtserver.swaggerhub.com/swexception4/OpenAPI/0.1.0/products
- description: serverless offline
  url: http://localhost:4000/dev/products

paths:
  /products:
    $ref: "products.yml"
  /products/{id}:
    $ref: "productsByID.yml"