get:
  summary: Get product details
  description: Return details about the product with the passed ID
  operationId: getPDP
  tags:
    - products
  parameters:
    - in: path
      name: id
      schema:
        type: string
      required: true
  responses:
    200:
      description: "product didn't found"
      content:
        application/json:
          schema:
            $ref: "../schemas/products.json#/responseProduct"
          example:
            {
              status: "success",
              data:
                {
                  id: "XYZ123",
                  name: "casetta",
                  description: "Casetta in legno massello adattata a tutte le temperature",
                  primaryPhoto: /image.jpg,
                  secondaryPhotos:
                    [
                      "/image.jpg",
                    ],
                  category: "casetta",
                  price: 9.99,
                  tax: 22,
                  show: true,
                  showHome: false,
                  stock: 123,
                },
            }
    400:
      description: "request error"
      content:
        application/json:
          schema:
            $ref: "../schemas/response.json#/response"
          example: { status: "error", message: "articolo non presente" }

patch:
  summary: Modify product
  description: Change information about the product specified with the ID
  tags:
    - products
  parameters:
    - in: header
      name: Authorization
      description: token JWT
      schema:
        type: string
      required: true
    - in: path
      name: id
      schema:
        type: string
      required: true
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: "../schemas/products.json#/editProduct"
        example: { id: "123VF", price: 8.00 }
  responses:
    200:
      description: "modify successful"
      content:
        application/json:
          schema:
            $ref: "../schemas/response.json#/response"
          example: { status: "success", message: "modifica riuscita" }
    400:
      description: "request error"
      content:
        application/json:
          schema:
            $ref: "../schemas/response.json#/response"
          example: { status: "error", message: "modifica non riuscita" }
          
delete:
  summary: Delete a product
  description: Remove the product with the specified ID
  tags:
    - products
  operationId: removeProduct
  parameters:
    - in: header
      name: Authorization
      description: token JWT
      schema:
        type: string
      required: true
    - in: path
      name: id
      schema:
        type: string
      required: true
    - in: query
      name: override
      schema:
        type: boolean
  responses:
    200:
      description: "Product removed"
      content:
        application/json:
          schema:
            $ref: "../schemas/response.json#/response"
          example: { status: "success", message: "Prodotto rimosso" }
    400:
      description: "request error"
      content:
        application/json:
          schema:
            $ref: "../schemas/response.json#/response"
          example: { status: "error", message: "si è verificato un errore" }
