get:
  summary: Get products
  description: Return the list of all the available products which respect filters
  tags:
    - products
  operationId: getProducts
  parameters:
    - in: query
      name: minPrice
      schema:
        type: integer
        format: int64
    - in: query
      name: maxPrice
      schema:
        type: integer
        format: int64
    - in: query
      name: category
      schema:
        type: string
    - in: query
      name: sorting
      schema:
        type: string
        enum: ["asc", "desc"]
    - in: query
      name: id-list
      description: "Array degli id dei prodotti che si vogliono ritornare"
      schema:
        type: array
        items:
          type: string
  responses:
    200:
      description: "product list"
      content:
        application/json:
          schema:
            $ref: "../schemas/products.json#/responseProducts"
          example:
            {
              status: "success",
              data:
                [
                  {
                    id: "123VF",
                    productName: "gioco",
                    description: "descrizione del prodotto",
                    primaryPhoto: /image.jpg,
                    secondaryPhotos:
                      [
                        "/image.jpg",
                      ],
                    category: "games",
                    netPrice: 5.99,
                    tax: 22,
                    show: true,
                    showHome: false,
                    stock: 123,
                  },
                  {
                    id: "321VF",
                    productName: "gioco2",
                    description: "descrizione del prodotto",
                    primaryPhoto: /image.jpg,
                    secondaryPhotos:
                      [
                        "/image.jpg",
                        "/image.jpg",
                      ],
                    category: "games",
                    netPrice: 7.99,
                    tax: 10,
                    show: true,
                    showHome: true,
                    stock: 0,
                  },
                ],
            }
    400:
      description: "request error"
      content:
        application/json:
          schema:
            $ref: "../schemas/response.json#/response"
          example: { status: "error", message: "richiesta fallita" }


post:
  summary: Add product
  description: Create a new product
  tags:
    - products
  parameters:
    - in: header
      name: Authorization
      description: token JWT
      schema:
        type: string
      required: true
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: "../schemas/products.json#/insertProduct"
        example:
          {
            productName: "scarpe",
            description: "queste sono delle bellissime scarpe",
            netPrice: 50.00,
            tax: 22,
            stock: 5,
          }
  responses:
    200:
      description: "Product inserted"
      content:
        application/json:
          schema:
            $ref: "../schemas/response.json#/response"
          example: { status: "success", message: "prodotto inserito" }
    400:
      description: "request error"
      content:
        application/json:
          schema:
            $ref: "../schemas/response.json#/response"
          example: { status: "error", message: "prodotto non inserito" }
